import Head from 'next/head'
import Image from 'next/image'
import Avatar from './components/Avatar'
import { MicrophoneIcon, SearchIcon, ViewGridIcon } from '@heroicons/react/solid'
import Footer from './components/Footer'
import { useRef } from 'react'
import { useRouter } from 'next/router'
export default function Home() {
  const searchRef=useRef(null)
  const router =useRouter()
  const search = (e) => {

    e.preventDefault();
    const term=searchRef.current.value;
    if(!term) return;
    
    router.push(`/search?term=${term}&start=0`);

  }
  return (
    <div className="flex flex-col items-center justify-center h-screen   ">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="flex w-full justify-between p-5 text-sm text-gray-700">
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          <ViewGridIcon className="w-10 h-10 
          p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
          <Avatar url="https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" />
        </div>
      </header>

      {/* Body */}
      <form className="flex flex-col items-center flex-grow mt-44 w-4/5">
        <Image
          src="https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          width={300}
          height={100}
          alt="Google"
        />
        <div className="flex mt-5 
          w-full
          hover:shadow-lg
          focus-within:shadow-lg
          max-w-md
          rounded-full
          border border-gray-200
          px-5 py-3 items-center
          sm:max-w-xl
          lg:max-w-2xl
          "

        >
          <SearchIcon className="w-5 h-5 mr-3 text-gray-500
            
            "/>
          <input 
          ref={searchRef}
          type="text" placeholder="Search" className=" h-5 
            rounded-full focus:outline-none
            flex-grow
            " />

          <MicrophoneIcon className="w-5 h-5 ml-3 text-gray-500" />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 mt-8 justify-center 
        sm:space-x-4 sm:flex-row sm:space-y-0">
          <button onClick={search} className="btn">
            Google Search
          </button>
          <button onClick={search}
            className="btn">
            I&apos;m Feeling Lucky
          </button>
        </div>
      </form>

    
      <Footer />
    </div>
  )
}
